#!/usr/bin/perl

=head1 NAME

treemake - find and execute Makefiles in the folder tree

=head1 SYNOPSIS

	treemake

=head1 DESCRIPTION

=cut


use strict;
use warnings;

use Getopt::Long;
use Pod::Usage;

exit main();

sub main {
    my $help;
    GetOptions(
        'help|h' => \$help,
    ) or pod2usage;
    pod2usage if $help;
    
    die 'FIXME';
    
    return 0;
}
